### ISSUE TITLE
Language Settings

### ISSUE THREAD

**Issue by eddy-hj-kim** [gmfmi/searchinghost-easy#2]
Hi,

First of all, thank you for the great work!
I went through the instructions of both searchinghost and searchinghost-easy, but I could only find out that laguage settings are availalbe in searchinghost.
However, I really like searchinghost-easy and its basic template without feature images.

My blog will be written in English and Korean. Would you give me an advice to use searchinghost-easy with language settings?
Or if I must use searchinghost, could you let me know how to integrate the basic template with it?

I am looking forward to hearing from you. Thank you!

**Comment by gmfmi** [comment]
Hi @eddy-hj-kim,

Thank you, very happy to see that you are playing (and reading the docs!) with these solutions 😃

It is probably not clear enough in the documentation of SearchinGhostEasy but as it is built on top of SearchinGhost any existing configuration parameter in SearchinGhost is also available in its "Easy" version.

Basically, I think you will end up with a configuration that looks like this one:

```javascript
new SearchinGhostEasy({
    contentApiKey: '<CONTENT_API_KEY>',
    // ... your custom config params
    searchinghostOptions: {
        indexOptions: {
            split: /\s+/,
            encode: function(str) {
                var regexp_replacements = {
                    "a": /[àáâãäå]/g,"e": /[èéêë]/g,"i": /[ìíîï]/g,"o": /[òóôõöő]/g,
                    "u": /[ùúûüű]/g,"y": /[ýŷÿ]/g, "n": /ñ/g,"c": /[ç]/g,"s": /ß/g,
                    " ": /[-/]/g,"": /['!"#$%&\\()\*+,-./:;<=>?@[\]^_`{|}~]/g," ": /\s+/g,
                }
                str = str.toLowerCase();
                for (var key of Object.keys(regexp_replacements)) {
                    str = str.replace(regexp_replacements[key], key);
                }
                return str === " " ? "" : str;
            }
        }
    }
});
```

Let me know if that works for you

**Comment by eddy-hj-kim** [comment]
Hi @gmfmi,

Thank you for the prompt response.
I am happy to say that I have successfully installed SearchinGhostEasy in my blog as following your guide.

It is very cool as I expected. I hope a lot of Ghost users use this.
As far as I know, most search plugins released to the public don't support Korean, except for yours.
I would like to promote SearchinGhostEasy to Korean Ghost Users if I have a chance,

Again thank you for sharing this good plugin!
(You may be able to close this issue.)

**Comment by gmfmi** [comment]
Thank you for the nice words. I don't know if there is "a lot" of Ghost users using SearchinGhost but the number is growing according to the statistics 🙂

OK, so I close the issue.
