### ISSUE TITLE
Doesn't search the text anywhere in the post or the excerpt.

### ISSUE THREAD

**Issue by bershatsky** [gmfmi/searchinghost-easy#3]
I have it installed and have played with it and even your demo. All it searches are the titles and tags.

How can I have it search the whole post or the excerpt?

Thanks!

**Comment by gmfmi** [comment]
Hi @bershatsky, interesting issue but I cannot reproduce it.

As an example, when I search for "effective thinking" (which only exists in the post content) on the demo website, I get the single article that mention it ([this one](https://demo.ghost.io/the-purpose-of-education)).

Could you send me an example that do not work for you? It will help me to investigate
