### ISSUE TITLE
Tried it again after a year. Got it working, but…

### ISSUE THREAD

**Issue by bershatsky** [gmfmi/searchinghost-easy#4]
Using your code in the code injection footer, it doesn't search for tags. How can I enable this?

```<script src="https://cdn.jsdelivr.net/gh/gmfmi/searchinghost-easy@latest/dist/searchinghost-easy-backpack.js"></script>
<script>
    new SearchinGhostEasy({
        contentApiKey: 'xxxxxxxxxxx'
    });
</script>

**Comment by bershatsky** [comment]
Even looked here, and searching for "Chili" doesn't show all the articles with that tag: https://www.backtopack.fr/tag/chili/

Thanks!

**Comment by gmfmi** [comment]
Hi @bershatsky,

Well, in fact, it actually search through tags. For example, if you try to search for `fables` on the demo website https://gmfmi.github.io/searchinghost-easy/backpack, one result will show up and the word "fables" does not exist in the article.

I agree with you, on my personal blog, is does not work on "chili" but it is related to a lot more subtle bug from the underlying search engine used by SearchinGhost. This bug will probably be solved by a version upgrade.

To see the progress, subscribe to this pull request https://github.com/gmfmi/searchinGhost/pull/15. I don't have much time right now but stay tuned.
